### ISSUE TITLE
pip install fail

### ISSUE THREAD

**Issue by buxx** [troelsfr/Gasp#2]
Hi, 
pip installation of Gasp fail:

```
Downloading/unpacking gasp
  Downloading gasp-0.4.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/gasp/setup.py) egg_info for package gasp
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_root/gasp/setup.py", line 20, in <module>
        read('CHANGES.txt')
      File "/tmp/pip_build_root/gasp/setup.py", line 5, in read
        text = open(os.path.join(os.path.dirname(__file__), *rnames)).read()
    IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/gasp/CHANGES.txt'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_root/gasp/setup.py", line 20, in <module>

    read('CHANGES.txt')

  File "/tmp/pip_build_root/gasp/setup.py", line 5, in read

    text = open(os.path.join(os.path.dirname(__file__), *rnames)).read()

IOError: [Errno 2] No such file or directory: '/tmp/pip_build_root/gasp/CHANGES.txt'

----------------------------------------
Cleaning up...
```

`CHANGES.txt` seems to be delete.

**Comment by troels-im** [comment]
Probably pip is installing this package:
https://pypi.python.org/pypi/gasp/0.3.3
http://wiki.laptop.org/go/GASP

I did not put Gasp in pypi respotory manually.

**Comment by buxx** [comment]
You got it ! ^^
